// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvmnxLMFTe7sd5VQGDx6AABrGnM_ThFdA',
    appId: '1:1018800110769:web:4342d38b22551d01fe7690',
    messagingSenderId: '1018800110769',
    projectId: 'eduventurevideocall',
    authDomain: 'eduventurevideocall.firebaseapp.com',
    storageBucket: 'eduventurevideocall.appspot.com',
    measurementId: 'G-JJQGLFZ1Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe-TOae5wncaxWCBl7pcAd12eWQ54L8TY',
    appId: '1:1018800110769:android:f16d9fdee82ce043fe7690',
    messagingSenderId: '1018800110769',
    projectId: 'eduventurevideocall',
    storageBucket: 'eduventurevideocall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6mG8WKFD248GikJFK_mUvTbHOtFzeOlk',
    appId: '1:1018800110769:ios:7a689551f9b4b95dfe7690',
    messagingSenderId: '1018800110769',
    projectId: 'eduventurevideocall',
    storageBucket: 'eduventurevideocall.appspot.com',
    iosBundleId: 'com.example.eduventureVideoCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6mG8WKFD248GikJFK_mUvTbHOtFzeOlk',
    appId: '1:1018800110769:ios:b9d7ad5bca64472bfe7690',
    messagingSenderId: '1018800110769',
    projectId: 'eduventurevideocall',
    storageBucket: 'eduventurevideocall.appspot.com',
    iosBundleId: 'com.example.eduventureVideoCall.RunnerTests',
  );
}
